#pragma once
#ifndef  _MY_BB_HEADER
#define _MY_BB_HEADER

#define BB_DEVICE_NAME L"\\Device\\myBBDevice"
#define BB_SYM_LNK_NAME L"\\??\\symLnkBBDevice"
#define IOCTL_PROC_CREATE_CALLBACK (ULONG) CTL_CODE(FILE_DEVICE_UNKNOWN,0x800,METHOD_BUFFERED,FILE_READ_ACCESS|FILE_WRITE_ACCESS)



#endif // ! _MY_BB_HEADER

